"use client";

// Single client boundary for Phosphor icons so both server and client
// components can pull them in without RSC friction.
export {
  House,
  SoccerBall,
  Trophy,
  FolderOpen,
  ChartDonut,
  Wallet,
  ChatCircleDots,
  Plus,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  PlayCircle,
  Coins,
  Brain,
  TrendUp,
  CheckCircle,
  Clock,
  LockSimple,
  ShareNetwork,
  ArrowCounterClockwise,
  Crown,
  Fire,
  Bell,
  MagnifyingGlass,
  CaretRight,
  Export,
  SealCheck,
  XCircle,
  X,
  CaretLeft,
  Envelope,
  Signature,
  ShieldCheck,
  ShieldStar,
  GoogleLogo,
  AppleLogo,
  XLogo,
  WarningCircle,
  Confetti,
  Sparkle,
  CursorClick,
  Target,
  Question,
  Gear,
  SignOut,
  DownloadSimple,
  ArrowUpRight,
  Bank,
  CreditCard,
  Lightning,
  HandWaving,
} from "@phosphor-icons/react";
